# Generated by Django 3.2.16 on 2023-05-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.SmallIntegerField(default=1, verbose_name='Время приготовления (в минутах)'),
            preserve_default=False,
        ),
    ]
